In [2]:
# Naive Bayes Classification

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

# Classification - Assignment2 - Question 1


In [2]:
# Importing the dataset
#dataset = pd.read_csv('iris.csv')
from sklearn.datasets import load_iris
dataset = load_iris()

In [10]:
# Visualize the data
#dataset.head()
dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
# Question 1 -- > Extract X as all columns except the last column and Y as last column.
#Spliting the dataset in independent and dependent variables
#X = dataset.iloc[:,:4].values
#y = dataset['species'].values
X = dataset.data
y = dataset.target

In [13]:
#Visualize the X -- values and Y value as target
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [14]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [26]:
list(dataset.target_names)

['setosa', 'versicolor', 'virginica']

In [15]:
# Create a Naïve Bayes Classification model to predict the species of flowers with explanation of parameters. (2 marks)
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [16]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [18]:
y_pred_train = nvclassifier.predict(X_train)

In [19]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

[2 2 0 0 0 2 1 1 1 1 1 2 0 0 0 0 2 1 0 1 0 2 0 2 2 1 2 0 2 1]


In [20]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0  8  1]
 [ 0  1  9]]


In [21]:

#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))

('Correct predictions: ', 28)
('False predictions', 2)
('\n\nAccuracy of the Naive Bayes Clasification is: ', 0)


In [22]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
def summarize_classification(y_test, y_pred):
    
    acc = accuracy_score(y_test, y_pred, normalize=True)
    num_acc = accuracy_score(y_test, y_pred, normalize=False)

    prec = precision_score(y_test, y_pred,average='macro')
    recall = recall_score(y_test, y_pred,average='macro')
    
    return {'accuracy': acc, 
            'precision': prec,
            'recall':recall, 
            'accuracy_count':num_acc}

In [23]:
test_classification = summarize_classification(y_test, y_pred);
test_classification

{'accuracy': 0.9333333333333333,
 'accuracy_count': 28,
 'precision': 0.9296296296296296,
 'recall': 0.9296296296296296}

In [24]:
train_classification = summarize_classification(y_train, y_pred_train);
train_classification

{'accuracy': 0.9666666666666667,
 'accuracy_count': 116,
 'precision': 0.9670731707317074,
 'recall': 0.9670731707317074}

# Classification - Assignment 2 - Question 2

In [30]:
# Classification - Assignment2
# Logistic Regression

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
# Importing the dataset
cardataset = pd.read_csv('car.data')

In [32]:
cardataset.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [33]:
# Let's add the columns to the dataset
cardataset.columns = ['Buying','Maintenance','Doors','Persons','Lug_Boot','Safety','Class']

In [34]:
cardataset.head()

Buying Maintenance Doors Persons Lug_Boot Safety  Class
0  vhigh       vhigh     2       2    small    med  unacc
1  vhigh       vhigh     2       2    small   high  unacc
2  vhigh       vhigh     2       2      med    low  unacc
3  vhigh       vhigh     2       2      med    med  unacc
4  vhigh       vhigh     2       2      med   high  unacc

## Converting the values of Class and other target variables to numerical values
## This is important to do so that the accuracy of the Algorithm is good

In [35]:
cleanup_nums = {"Class":     {"unacc": 4, "acc": 3,'good': 2,'vgood':1}
                }
cardataset.replace(cleanup_nums,inplace = True)


In [36]:
target = cardataset['Class']
cardataset.drop( ['Class'],axis = 1,inplace = True)

In [37]:
cardataset = pd.get_dummies(cardataset)
cardataset.head()

Buying_high  Buying_low  Buying_med  Buying_vhigh  Maintenance_high  \
0            0           0           0             1                 0   
1            0           0           0             1                 0   
2            0           0           0             1                 0   
3            0           0           0             1                 0   
4            0           0           0             1                 0   

   Maintenance_low  Maintenance_med  Maintenance_vhigh  Doors_2  Doors_3  ...  \
0                0                0                  1        1        0  ...   
1                0                0                  1        1        0  ...   
2                0                0                  1        1        0  ...   
3                0                0                  1        1        0  ...   
4                0                0                  1        1        0  ...   

   Doors_5more  Persons_2  Persons_4  Persons_more  Lug_Boot_big  \
0            0          1          0             0             0   
1            0          1          0             0             0   
2            0          1          0             0             0   
3            0          1          0             0             0   
4            0          1          0             0             0   

   Lug_Boot_med  Lug_Boot_small  Safety_high  Safety_low  Safety_med  
0             0               1            0           0           1  
1             0               1            1           0           0  
2             1               0            0           1           0  
3             1               0            0           0           1  
4             1               0            1           0           0  

[5 rows x 21 columns]

In [38]:
from sklearn.model_selection import train_test_split

X = cardataset
Y = target

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [39]:
x_train.shape, y_train.shape

((1381, 21), (1381,))

In [40]:
x_test.shape, y_test.shape

((346, 21), (346,))

In [41]:
cardataset.dtypes

Buying_high          uint8
Buying_low           uint8
Buying_med           uint8
Buying_vhigh         uint8
Maintenance_high     uint8
Maintenance_low      uint8
Maintenance_med      uint8
Maintenance_vhigh    uint8
Doors_2              uint8
Doors_3              uint8
Doors_4              uint8
Doors_5more          uint8
Persons_2            uint8
Persons_4            uint8
Persons_more         uint8
Lug_Boot_big         uint8
Lug_Boot_med         uint8
Lug_Boot_small       uint8
Safety_high          uint8
Safety_low           uint8
Safety_med           uint8
dtype: object

In [42]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(penalty='l2', C=1.0, solver='liblinear', multi_class='auto').fit(x_train, y_train)

Explanation of the Parameters

1. penalty{‘l1’, ‘l2’, ‘elasticnet’, ‘none’}, default=’l2’
	Used to specify the norm used in the penalization. The ‘newton-cg’, ‘sag’ and ‘lbfgs’ solvers support only l2 penalties. ‘elasticnet’ is only supported by the ‘saga’ solver. If ‘none’ (not supported by the liblinear solver), no regularization is applied.

2.	Cfloat, default=1.0
	Inverse of regularization strength; must be a positive float. 
	Smaller values specify stronger regularization.

3.	solver{‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’}, default=’lbfgs’
	Algorithm to use in the optimization problem.

	For small datasets, ‘liblinear’ is a good choice, whereas ‘sag’ and ‘saga’ are faster for large ones.

	For multiclass problems, only ‘newton-cg’, ‘sag’, ‘saga’ and ‘lbfgs’ handle multinomial loss; ‘liblinear’ is limited to one-versus-rest schemes.

	‘newton-cg’, ‘lbfgs’, ‘sag’ and ‘saga’ handle L2 or no penalty

	‘liblinear’ and ‘saga’ also handle L1 penalty

	‘saga’ also supports ‘elasticnet’ penalty

	‘liblinear’ does not support setting penalty='none'

	Note that ‘sag’ and ‘saga’ fast convergence is only guaranteed on features with approximately the same scale. You can preprocess the data with a scaler from sklearn.preprocessing.


4.	multi_class{‘auto’, ‘ovr’, ‘multinomial’}, default=’auto’
	 For ‘multinomial’ the loss minimised is the multinomial loss fit across the entire probability distribution, even when the data is binary. ‘multinomial’ is unavailable when solver=’liblinear’. ‘auto’ selects ‘ovr’ if the data is binary, or if solver=’liblinear’, and otherwise selects ‘multinomial’.




In [43]:
# Perform the 10 Fold Cross Validation
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
kf = KFold(n_splits=10,shuffle=True, random_state=123)
cv_scores = cross_val_score(logistic_model,x_train,y_train,cv=kf)
cv_scores

array([0.89208633, 0.86956522, 0.87681159, 0.89130435, 0.87681159,
       0.86956522, 0.89130435, 0.82608696, 0.84782609, 0.83333333])

In [44]:
cv_scores.mean()

0.8674695026587426

In [45]:
logistic_model.fit(x_train,y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [49]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
def summarize_classification(y_test, y_pred):
    
    acc = accuracy_score(y_test, y_pred, normalize=True)
    num_acc = accuracy_score(y_test, y_pred, normalize=False)

    prec = precision_score(y_test, y_pred,average='macro')
    recall = recall_score(y_test, y_pred,average='macro')
    
    return {'accuracy': acc, 
            'precision': prec,
            'recall':recall, 
            'accuracy_count':num_acc}

In [50]:
y_pred_train = logistic_model.predict(x_train)

In [51]:
# Predicting the Test set results
y_pred = logistic_model.predict(x_test)
print(y_pred)

[3 4 4 4 3 4 4 4 4 3 3 3 4 4 4 3 4 4 4 3 4 3 4 4 4 4 4 4 3 4 3 3 4 4 2 4 4
 4 4 4 1 4 4 3 4 4 3 4 4 4 3 4 4 1 4 4 3 4 3 4 4 4 1 4 4 3 4 3 4 4 4 4 3 4
 4 4 4 2 4 4 3 4 3 4 4 3 4 4 4 4 4 4 3 4 4 4 4 4 1 4 4 3 4 3 3 4 4 3 4 4 3
 4 4 3 4 3 3 4 4 4 4 4 4 4 3 4 4 2 4 4 3 3 4 3 4 4 4 4 4 3 3 4 4 4 4 3 4 3
 4 4 4 4 4 3 4 3 3 4 4 3 3 4 4 3 4 4 4 4 4 4 4 4 3 4 4 3 4 4 3 4 4 4 4 4 4
 4 4 4 3 4 4 3 4 4 3 3 4 4 3 4 4 4 4 4 3 4 4 4 3 4 4 3 3 2 4 4 4 4 4 4 3 3
 4 4 3 3 3 4 4 3 3 4 4 4 4 4 4 4 4 4 3 3 3 3 4 4 4 4 4 3 4 4 3 4 4 4 4 4 3
 3 4 4 3 4 4 4 4 4 4 4 4 4 4 4 1 3 4 4 4 4 4 4 3 3 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 3 4 4 3 4 4 4 4 4 4 3 4 4 2 3 4 3 2 3 4 4 4 4 4 3 4 3 3 3 4 4 4 3 4 4
 1 4 4 3 4 4 4 3 4 4 3 4 4]


In [52]:
test_classification = summarize_classification(y_test, y_pred);
test_classification

{'accuracy': 0.8728323699421965,
 'accuracy_count': 302,
 'precision': 0.7839025500910748,
 'recall': 0.6002763229163645}

In [53]:
train_classification = summarize_classification(y_train, y_pred_train);
train_classification

{'accuracy': 0.8855901520637219,
 'accuracy_count': 1223,
 'precision': 0.822258846429398,
 'recall': 0.6159908712701382}

In [54]:
# Confusion Matrix
pred_results = pd.DataFrame({'y_test': y_test,
                                 'y_pred': y_pred})
    
model_crosstab = pd.crosstab(pred_results.y_pred, pred_results.y_test)
model_crosstab

y_test   1  2   3    4
y_pred                
1        6  0   0    0
2        0  3   3    0
3       10  8  62   10
4        0  0  13  231